### ISSUE TITLE
Upgrade to Select2 4.0.0

### ISSUE THREAD

**Issue by nbuytaert1** [nbuytaert1/apex-select2#33]
Wait for a stable version first.

**Comment by cboillat** [comment]
Is it stable enough now to upgrade ?

**Comment by nbuytaert1** [comment]
Select2 version 4.0.0 is stable indeed. However, it's a significant upgrade which requires me to change the APEX plugin code as well. I don't have much time these days, so I'm afraid this will be something for later.

**Comment by cboillat** [comment]
Ok no problem I understand. Thx anyway for your great plugin :)

**Comment by sapreuss** [comment]
Hi.
I enjoy and use your plugin in several projects. I found out, that Select2 V4 better supports my requirements and so I took a look at your plugin implementation.

There are only a few changes in your code to enable select2 V4!

I did not test the tagging support (since i don't need it), but I tested the standards including the remote lazy load with infinite scroll.

Thx for your great work!

I'm sorry I cant attach the with the changes. Are you interested?

**Comment by glebovpavel** [comment]
Hallo sapreuss! 
Thanks for your work.
Works multiselect - feature with your improvements?

**Comment by sapreuss** [comment]
Hi Pavel,

 

yes – it works. 

 

My requirement is changing the multiselect content by trigger (return value of a modal dialog) with a remote data source.

 

See the changes; I might add some work, because my customers need this feature.

 

Current source is appended.

 

Freundliche Grüße

Sebastian Preuß

Dipl. Ing. Sebastian A. Preuß @ Consultant - Project Management - Oracle Database Management - Oracle Application Express




 

Von: Pavel [mailto:notifications@github.com] 
Gesendet: Freitag, 16. Oktober 2015 12:45
An: nbuytaert1/apex-select2 <apex-select2@noreply.github.com>
Cc: sapreuss <sapreuss@input98.de>
Betreff: Re: [apex-select2] Upgrade to Select2 4.0.0 (#33)

 

Hallo sapreuss! 
Thanks for your work.
Works multiselect - feature with your improvements?

**Comment by nbuytaert1** [comment]
Hello Sebastian,

I sure am interested in your work. Is it possible for you to attach the plugin file(s) to this thread?

Thanks,
Nick

**Comment by sapreuss** [comment]
Hi Nick,

 

Sure.  Did you receive it?

 

The plugin includes the current select2 sources and the (very few) Changes.

It did not use the compatibility code but add the debug feature in the add library for testing.

 

I will do some more testing. But I’m not interested in the tagging feature… :-( 

 

So this is never even tried.

 

I’m glad if it helps!

 

Sebastian

 

Von: Nick Buytaert [mailto:notifications@github.com] 
Gesendet: Montag, 19. Oktober 2015 13:24
An: nbuytaert1/apex-select2 <apex-select2@noreply.github.com>
Cc: sapreuss <sapreuss@input98.de>
Betreff: Re: [apex-select2] Upgrade to Select2 4.0.0 (#33)

 

Hello Sebastian,

I sure am interested in your work. Is it possible for you to attach the plugin file(s) to this thread?

Thanks,
Nick

**Comment by nbuytaert1** [comment]
I can't see the file that you are trying to share. Probably because you are replying to this thread via e-mail. Can you try to attach the file(s) directly to the GitHub thread?

**Comment by sapreuss** [comment]
I already tried this. Butter you can only Dropbox images. I am not in my Office today. Let's try tomorrow. 


Sebastian Preuß von unterwegs 





On Mon, Oct 19, 2015 at 10:21 PM -0700, "Nick Buytaert" <notifications@github.com> wrote:












I can't see the file that you are trying to share. Probably because you are replying to this thread via e-mail. Can you try to attach the file(s) directly to the GitHub thread?

**Comment by sapreuss** [comment]
Hi Nick,

 

the file will be available on:

 

  https://www.hidrive.strato.com/lnk/gKPEKWZv

 

for the next 10 days.

 

Regards Sebastian

 

Von: Nick Buytaert [mailto:notifications@github.com] 
Gesendet: Dienstag, 20. Oktober 2015 07:22
An: nbuytaert1/apex-select2 <apex-select2@noreply.github.com>
Cc: sapreuss <sapreuss@input98.de>
Betreff: Re: [apex-select2] Upgrade to Select2 4.0.0 (#33)

 

I can't see the file that you are trying to share. Probably because you are replying to this thread via e-mail. Can you try to attach the file(s) directly to the GitHub thread?

**Comment by nbuytaert1** [comment]
Thanks, I downloaded it. I'll take a look at it as soon as I find some spare time.

**Comment by nbuytaert1** [comment]
Upgraded the APEX plugin to work with Select2 v4.0.3.
