### ISSUE TITLE
Starting search with numbers

### ISSUE THREAD

**Issue by mendesn** [nbuytaert1/apex-select2#63]
Hi,

When the search starting is a number its always saying "The results could not be loaded".

e.g
in the table we have
1031-20 Hello
1301-21 there
1301-22 nice LOV

LOV
Starting search
1031
"The results could not be loaded"

You have to start searching with the same start from the LOV.

Thanks,
Nelson

**Comment by mendesn** [comment]
Hi,

It seems if you put a row count on Lazy option it works fine.

Thanks,
Nelson

**Comment by nbuytaert1** [comment]
Hi Nelson,

Putting a row count on the lazy option? I don't understand that.

I assume you are seeing the message _The results could not be loaded_ only when lazy loading is enabled. Do the search results eventually come through or nothing at all?

When you type in a search term, an AJAX request is performed to fetch the LOV records that match the search term. A new AJAX request gets fired as soon as you change the search term. The first AJAX request gets invalidated if it was still running at that moment. I believe you're seeing the _The results could not be loaded_ message as a result of the invalidated AJAX request. You should get back a result from the second AJAX request though. This will hide the error message and display the matched LOV records from the second search term.

This behavior is difficult to fix for me since it's part of the Select2 jQuery plugin, which is pretty _black box_ for me.

Nick

**Comment by mendesn** [comment]
I will reply later with print screens

Em 03/08/2016 19:52, "Nick Buytaert" <notifications@github.com> escreveu:

**Comment by mendesn** [comment]
It is a very good plug-in

Thanks

**Comment by nbuytaert1** [comment]
I have tried to reproduce your issue, but I couldn't find anything wrong. Feel free to create a test case on apex.oracle.com. That makes it easier for me to take a look at the problem.

**Comment by mendesn** [comment]
The behavior is different on APEX 5, Im using 4.2.
But you can take a look, start with numbers... 

NEOON
MENDES.NELSON@GMAIL.COM
1234

**Comment by nbuytaert1** [comment]
Your LOV query was invalid.
```sql
select ename, ename
from emp
order by 1
```
_Column name "ENAME" is already used in the SQL query. Make sure that you use unique alias names for your columns._

Always alias your LOV columns. That fixes the unique alias problem.
```sql
select ename as d,
       ename as r
from emp
order by 1
```
Then I notice the _error loading..._ message as described in one of my previous comments. While typing in a search term, it might happen that an AJAX request gets cancelled. That's the reason behind the _error loading..._ message. But in the end, the search results come through.

This is something I can't fix because it's originating from the Select2 jQuery plugin, not the APEX plugin.

**Comment by nbuytaert1** [comment]
Here's an [issue](https://github.com/select2/select2/issues/4402) from the official Select2 repository that discusses the same matter.

I'll increase the [delay](https://select2.github.io/options.html#a-request-is-being-triggered-on-every-key-stroke-can-i-delay-th) AJAX parameter from 250 to 400 milliseconds to prevent cancelled AJAX requests.

**Comment by mendesn** [comment]
Hi,

Thank you for figure that out.
Great job

Thanks,
Nelson

**Comment by nbuytaert1** [comment]
> Which version?

Version 3.0.2.
