### ISSUE TITLE
Quickpick no longer working in 3.0.3

### ISSUE THREAD

**Issue by jeffreykemp** [nbuytaert1/apex-select2#84]
Select2 plugin 3.0.3 installed
Apex 5.0.3 (also reproduced in 5.1.2)

Lazy Load = Yes
Show Quick Picks = Yes
Label 1 = description of chosen value
Value 1 = code of chosen value

Clicking the quickpick seems to fire any dynamic actions but the value of the item is not changed nor shown.

Demo: https://apex.oracle.com/pls/apex/f?p=67465:3:0

**Comment by jeffreykemp** [comment]
This was previously working when we were on Select2 2.6 previously.

**Comment by jeffreykemp** [comment]
Workaround: remove the Lazy Load option on the item

**Comment by nbuytaert1** [comment]
Hi Jeffrey,

Apologies for the late reply.

The action behind the Quick Pick options is the standard `$s` function. In some cases, the `$s` function will successfully set the value for a Select2 item. However, using more advanced plugin settings will cause the Quick Pick options to no longer work. The reason is that "advanced" Select2 items need custom JavaScript code to set their value. When lazy loading is enabled for example, you'll have to do something like this:

``` javascript
$('#P10_MY_SELECT2_ITEM').append(
  $('<option>', {
    value: 7900,
    text: 'James'
  }).attr('selected', 'selected')
).trigger('change');
```
